using System.Collections.Generic;

namespace VisualEQ.SpawnSystem
{
    // Human-readable names for the numeric IDs the DB stores for race, class, body type,
    // and gender. Separate from RaceModelMapper (which is about model resolution) — this
    // is display-only. Unknown IDs fall back to a generic label so unusual values still
    // show something.
    public static class SpawnInfoLookups
    {
        public static string RaceName(int race) =>
            Races.TryGetValue(race, out var n) ? n : $"Race {race}";

        public static string ClassName(int cls) =>
            Classes.TryGetValue(cls, out var n) ? n : $"Class {cls}";

        public static string BodyTypeName(int bt) =>
            BodyTypes.TryGetValue(bt, out var n) ? n : $"Body {bt}";

        public static string GenderName(int gender)
        {
            switch (gender)
            {
                case 0:  return "Male";
                case 1:  return "Female";
                case 2:  return "Neuter";
                default: return $"Gender {gender}";
            }
        }

        // Race labels — kept aligned with RaceModelMapper. Where a race is used
        // in the DB for something that doesn't match its canonical EQEmu name
        // (e.g. race 20 canonically "Trakanon Chief" but populated with Venril
        // Sathir in this data), the label reflects the DB usage.
        static readonly Dictionary<int, string> Races = new Dictionary<int, string>
        {
            {   1, "Human" },              {   2, "Barbarian" },
            {   3, "Erudite" },            {   4, "Wood Elf" },
            {   5, "High Elf" },           {   6, "Dark Elf" },
            {   7, "Half Elf" },           {   8, "Dwarf" },
            {   9, "Troll" },              {  10, "Ogre" },
            {  11, "Halfling" },           {  12, "Gnome" },
            {  13, "Aviak" },              {  14, "Werewolf" },
            {  15, "Brownie" },            {  16, "Centaur" },
            {  17, "Golem" },              {  18, "Giant" },
            {  19, "Trakanon" },           {  20, "Venril Sathir" },
            {  21, "Evil Eye" },           {  22, "Beetle" },
            {  23, "Kerran" },             {  24, "Fish" },
            {  25, "Faerie" },             {  26, "Froglok" },
            {  27, "Froglok Ghoul" },      {  28, "Sporali" },
            {  29, "Gargoyle" },           {  30, "Evil Eye (variant)" },
            {  31, "Gelatinous Cube" },    {  32, "Dragon (Kunark)" },
            {  33, "Ghoul" },              {  34, "Bat" },
            {  36, "Rat" },                {  37, "Snake" },
            {  38, "Spider" },             {  39, "Gnoll" },
            {  40, "Goblin (Pickclaw)" },  {  41, "Gorilla" },
            {  42, "Wolf" },               {  43, "Bear" },
            {  44, "Freeport Guard" },     {  45, "Demi Lich" },
            {  46, "Imp / Familiar" },     {  47, "Griffin" },
            {  48, "Kobold" },             {  49, "Elder Dragon" },
            {  50, "Lion" },               {  51, "Lizardman" },
            {  52, "Mimic" },              {  53, "Minotaur" },
            {  54, "Orc" },                {  55, "Human Beggar" },
            {  56, "Pixie" },              {  57, "Drachnid" },
            {  58, "Solusek Ro" },         {  59, "Bloodgill Goblin" },
            {  60, "Skeleton" },           {  61, "Shark" },
            {  62, "Tunare" },             {  63, "Evil Eye (variant 2)" },
            {  64, "Treant" },             {  65, "Vampire" },
            {  66, "Rallos Zek" },         {  67, "Iksar/Highpass Guard" },
            {  68, "Tentacle Terror" },    {  69, "Willowisp" },
            {  70, "Zombie" },             {  71, "Human Guard" },
            {  72, "Ship" },               {  73, "Launch (Skiff)" },
            {  74, "Piranha" },            {  75, "Elemental" },
            {  76, "Puma / Plains Cat" },  {  77, "Iksar Citizen" },
            {  78, "Erudite Citizen" },    {  79, "Bixie" },
            {  80, "Reanimated Hand" },    {  81, "Halfling Deputy" },
            {  82, "Scarecrow" },          {  83, "Skunk" },
            {  85, "Skeleton (pet)" },     {  86, "Sphinx" },
            {  87, "Armadillo" },          {  88, "Clockwork Gnome" },
            {  89, "Drake" },              {  90, "Barbarian Ghost" },
            {  91, "Basilisk" },           {  92, "Erudite Ghost" },
            {  93, "Innkeeper / Bouncer" },{  94, "Qeynos Guard" },
            {  95, "Avatar of Fear" },     {  96, "Cockatrice" },
            {  98, "Dhampyre" },           {  99, "Amygdalan" },
            { 100, "Rock Dervish" },       { 101, "Efreeti" },
            { 102, "Froglok Tadpole" },    { 103, "Phinigel Autropos" },
            { 104, "Leech" },              { 105, "Swordfish" },
            { 106, "Human Guard (variant)" }, { 107, "Elephant" },
            { 108, "Eye of Zomm" },        { 109, "Wasp / Yellowjacket" },
            { 110, "Mermaid" },            { 111, "Harpy" },
            { 112, "Freeport Merchant" },  { 113, "Fae Drake" },
            { 114, "Ghost" },              { 116, "Seahorse" },
            { 117, "Human Champion" },     { 118, "City Spirit" },
            { 119, "Sabertooth Cat" },     { 120, "Spirit Wolf" },
            { 121, "Gorgalosk" },          { 122, "Horror Construct" },
            { 123, "Innoruuk" },           { 124, "Nightmare" },
            { 125, "Quillmane" },          { 126, "Storm Mistress" },
            { 127, "Invisible / Summoned" },{ 128, "Iksar Broodling" },
            { 129, "Scorpion" },           { 130, "Human (Taruun)" },
            { 131, "Sarnak" },             { 133, "Drolvarg" },
            { 134, "Mosquito" },           { 135, "Rhino (Kunark)" },
            { 136, "Xalgoz" },             { 137, "Goblin" },
            { 138, "Skulking Brute" },     { 139, "Iksar Bandit" },
            { 140, "Forest Giant" },       { 141, "Boat" },
            { 144, "Burynai" },            { 145, "Ooze" },
            { 146, "Spectral Guardian" },  { 147, "Guardian of Xalgoz" },
            { 148, "Barracuda" },          { 149, "Scorpikis" },
            { 150, "Erollisi Marr" },      { 151, "Tribunal" },
            { 153, "Bristlebane" },        { 154, "Chromadrac" },
            { 155, "Skeleton (barbed)" },  { 156, "Ratman" },
            { 157, "Wyvern" },             { 158, "Wurm" },
            { 159, "Insatiable Gnawer" },  { 160, "Sebilite Golem" },
            { 161, "Scalebone Skeleton" }, { 162, "Man-Eating Plant" },
            { 163, "Raptor" },             { 164, "Sathir Construct" },
            { 165, "Praklion / Faydedar" },{ 166, "Cursed Hand" },
            { 167, "Succulent Plant" },    { 168, "Holgresh" },
            { 169, "Brontotherium" },      { 170, "Shadow Guardian" },
            { 171, "Direwolf" },           { 172, "Manticore" },
            { 173, "Entoling" },           { 174, "Ice Shade" },
            { 175, "Armored Shadow" },     { 176, "Rabbit" },
            { 177, "Walrus" },             { 178, "Geonid" },
            { 181, "Tizmak" },             { 183, "Coldain Dwarf" },
            { 184, "Velious Dragon" },     { 185, "Kobold (variant)" },
            { 187, "Siren" },              { 188, "Frost Giant" },
            { 189, "Storm Giant" },        { 190, "Shellfish Collector" },
            { 191, "Panda" },              { 193, "Tserrina Syl`Tor" },
            { 194, "Tortoise" },           { 195, "Zlandicar" },
            { 196, "Wraith" },             { 198, "Kerafyrm" },
            { 199, "Shik`Nar" },           { 200, "Rockhopper" },
            { 201, "Underbulk" },          { 202, "Grimling" },
            { 203, "Xakra" },              { 205, "Shadel Bandit" },
            { 206, "Owlbear" },            { 207, "Rhinobeetle" },
            { 208, "Coterie Vampyre" },    { 209, "Elemental Warrior" },
            { 210, "Steam Elemental" },    { 211, "Essence Spirit" },
            { 212, "Fire Construct" },     { 213, "Wetfang / Minnow" },
            { 214, "Thought Leech" },      { 215, "Bogling" },
            { 217, "Shissar" },            { 218, "Fungal Fiend" },
            { 219, "Coldain (variant)" },  { 220, "Stonegrabber" },
            { 221, "Scarlet Cheetah" },    { 222, "Zelniak" },
            { 223, "Lightcrawler" },       { 224, "Xakra (variant)" },
            { 225, "Sunflower" },          { 226, "Khati Sha" },
            { 227, "Saprophyte" },         { 228, "Caller" },
            { 229, "Netherbian" },         { 230, "Aten Ha Ra" },
            { 231, "Grieg Veneficus" },    { 232, "Sonic Wolf" },
            { 233, "Elemental (Wind/Flame/Sand)" },
            { 234, "Skeletal Minion" },    { 235, "Savage Mutant" },
            { 236, "Lord Inquisitor Seru" },
            { 237, "Wandering Fanatic" },  { 238, "King Kerrath" },
            { 239, "Spiritual Arcanist" }, { 240, "Narandi the Wretched" },
            { 241, "Nightstalker" },       { 242, "Potameid" },
            { 243, "Dryad" },              { 244, "Treant (variant)" },
            { 245, "Tsetsian Fly" },       { 246, "Coirnav" },
            { 248, "Clockwork Golem" },    { 249, "Manaetic Prototype" },
            { 250, "Banshee" },            { 253, "Grummus" },
            { 259, "Tar`Dak" },            { 260, "Bat (variant)" },
            { 261, "Hraquis" },            { 263, "Tin Soldier" },
            { 264, "Wraith (variant)" },   { 265, "Malarian" },
            { 266, "Knight of Pestilence" },
            { 267, "Guardian of Pestilence" },
            { 268, "Rallius Rattican" },   { 269, "Bubonian" },
            { 270, "Wretched Pusling" },   { 271, "Triloun" },
            { 272, "Stormrider" },         { 274, "Clockwork (erratic)" },
            { 275, "Manaetic Behemoth" },  { 276, "Clockwork Device" },
            { 277, "Hobgoblin" },          { 278, "Karana / Agnarr" },
            { 279, "Blood Raven" },        { 280, "Gargoyle (Velious)" },
            { 286, "Mujaki" },             { 287, "Shadow Steed" },
            { 294, "Mephit" },             { 297, "Vhaksiz the Shade" },
            { 302, "Regrua" },             { 305, "Grezlan" },
            { 306, "Jord Militis" },       { 307, "Vann Stav" },
            { 308, "Brann Militis" },      { 309, "Vind Militis" },
            { 310, "Relv" },               { 311, "Evynd Firestorm" },
            { 312, "Emmerik Skyfury" },    { 315, "Deepwater Kraken" },
            { 316, "Hurricane Lorok" },    { 321, "Broken Skull Boar" },
            { 324, "Foreboding Guardian" },{ 326, "Virulent Arachnid" },
            { 329, "Storm Portal" },       { 330, "Halfling (Gubbly)" },
            { 331, "Broken Skull Troll" }, { 332, "Broken Skull Plunderer" },
            { 335, "Overlord Ngrub" },     { 336, "Spiritseeker Nadox" },
            { 337, "Broken Skull Blackhand" },
            { 338, "Gnome Plunderer" },    { 339, "Dark Elf Plunderer" },
            { 340, "Ogre Plunderer" },     { 341, "Human Plunderer" },
            { 342, "Erudite Plunderer" },  { 344, "Pestilent Zombie" },
            { 345, "Emissary of Hate" },   { 346, "Blackblooded Assassin" },
            { 347, "Luggald" },            { 348, "Drogmor" },
            { 351, "Templar of Hate" },    { 352, "Warlock of Hate" },
            { 353, "Initiate/Master" },    { 354, "Vessel/Animist" },
            { 355, "Highborn Commander" }, { 357, "Decaying Wolf" },
            { 371, "Shinta Knight" },      { 376, "Kobold Siege Supplies" },
            { 377, "Kobold Barrel" },      { 378, "Chest / Footlocker" },
            { 383, "Digested Remains" },   { 392, "Ukun" },
            { 394, "Ikaav" },              { 395, "Aneuk" },
            { 396, "Kyv" },                { 397, "Noc" },
            { 400, "Huvul" },              { 404, "Test Boat" },
            { 405, "Stoneworker" },        { 406, "Overlord Mata Muram" },
            { 407, "Lightning Warrior" },  { 409, "Bazu" },
            { 410, "Feran" },              { 411, "Dragorn Assassin" },
            { 412, "Chimera" },            { 413, "Dragorn" },
            { 414, "Murkglider" },         { 415, "Swamp Rat" },
            { 416, "Vampyre Bat" },        { 417, "Herrian" },
            { 418, "Discordling" },        { 419, "Girplan" },
            { 420, "Arch Magus Vangl" },   { 422, "Orb of Discord" },
            { 426, "Crystalline Portal" }, { 428, "Vermin Nest" },
            { 429, "Dormant Egg" },        { 432, "Flutterwing" },
            { 433, "Exhausted Goblin" },   { 440, "Gloom Spider" },
            { 441, "Queen Gloomfang" },    { 449, "Spider Cocoon" },
            { 455, "Gloomingdeep Warrior" },
            { 510, "Trap (invisible)" },   { 513, "Trap (variant)" },
            { 514, "Trap (variant 2)" },
        };

        static readonly Dictionary<int, string> Classes = new Dictionary<int, string>
        {
            {  0, "None" },
            {  1, "Warrior" }, {  2, "Cleric" }, {  3, "Paladin" }, {  4, "Ranger" },
            {  5, "Shadow Knight" }, {  6, "Druid" }, {  7, "Monk" }, {  8, "Bard" },
            {  9, "Rogue" }, { 10, "Shaman" }, { 11, "Necromancer" }, { 12, "Wizard" },
            { 13, "Magician" }, { 14, "Enchanter" }, { 15, "Beastlord" }, { 16, "Berserker" },
            { 20, "Warrior GM" }, { 32, "Bard GM" },
            { 40, "Merchant" }, { 41, "Adventure Recruiter" }, { 42, "Adventure Merchant" },
            { 60, "LDoN Recruiter" }, { 61, "LDoN Merchant" }, { 62, "Guild Bank" },
            { 63, "Rewards Merchant" }, { 65, "Discord Merchant" },
        };

        static readonly Dictionary<int, string> BodyTypes = new Dictionary<int, string>
        {
            {  0, "Undefined" }, {  1, "Humanoid" }, {  2, "Lycanthrope" }, {  3, "Undead" },
            {  4, "Giant" }, {  5, "Construct" }, {  6, "Extraplanar" }, {  7, "Magical" },
            {  8, "Summoned Undead" }, {  9, "Raid Giant" }, { 10, "Untargetable" },
            { 11, "Vampyre" }, { 12, "Atenha Ra" }, { 13, "Greater Akheva" },
            { 14, "Khati Sha" }, { 15, "Seru" }, { 16, "Draz Nurakk" }, { 17, "Zek" },
            { 18, "Luggald" }, { 19, "Animal" }, { 20, "Insect" }, { 21, "Reptile" },
            { 22, "Elemental / Planar" }, { 23, "Plant" }, { 24, "Dragon" },
            { 25, "Summoned2" }, { 27, "Special" }, { 33, "Muramite" },
        };
    }
}
